spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imageuploader?useSSL=false&autoReconnect=true&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  web:
    resources:
      static-locations: file:D:\code\projects\backendProjects\imageUploaderBackend\uploads
